# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 317fa9db0e249f81ecb8c6465cdfc54d45ee84fe215310897c0fdce49bf7ee57fbadfa25dedbc53e34bc234a5170a77d4d1b6e89ee8ddf375e53f7c7ccfce36d

test:
  secret_key_base: 41680850283a52e0de7fabdc882e6f8d2e994658f9b17a9414b7f9e1196784e08bebfb5a902679b70086879d58c9d46a730116ec8ef10214ec83ff453dc88fb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
